FROM node:22-alpine AS build
WORKDIR /app
COPY worker/package*.json ./
RUN npm ci
COPY worker/ .
RUN npx tsc

FROM node:22-alpine
WORKDIR /app
COPY --from=build /app/package*.json ./
RUN npm ci --omit=dev
COPY --from=build /app/dist ./dist
CMD ["node", "dist/index.js"]
